### PR TITLE
Fix Travis CI image

### PR DESCRIPTION
**Pull request by TransportLayer**

### CODE REVIEW

**Comment by Innectic** [comment]
Change the target branch to develop :D

**Comment by TransportLayer** [comment]
Did... did I break it?

**Comment by Innectic** [comment]
Nah, I'll just have to manually merge this since we've released some updates since the last time the `develop` branch was updated

**Comment by TransportLayer** [comment]
Ah, I see.
So, I won't get to be in the commit log? I worked hard editing those 6 characters! /s

**Comment by Innectic** [comment]
Took care of it in this commit. https://github.com/CactusDev/CactusBot/commit/ad9f804d058072325cb400b7341bcc2cda90c9dc

**Comment by TransportLayer** [comment]
RIP :(

**Pull request closed without merging**
