### PR TITLE
Fix arg duplication in a not hacky way

### LINKED ISSUE #203: User and Arg repeating?
Litterally exactly what I did.

misterjoker: !command add hug %USER% hugs %ARGS%
cactusbot:  Updated command !hug.
misterjoker: !hug @Alfred_E_Newman
cactusbot: misterjoker hugs @Alfred_E_Newman !hug @Alfred_E_Newman

### PR DESCRIPTION
**Pull request by Innectic**
Fixes #203

### CODE REVIEW

**Comment by Innectic** [comment]
@2Cubed It's something with the way that we split the `MessagePackets`. We're creating an array of `MessagePacket`. The last argument always contains that, I couldn't find out why. This is a fix that wouldn't require us to probably rewrite the whole splitter

**Comment by 2Cubed** [comment]
@Innectic I just ran some tests, and it looks like `MessagePacket.split()` is fine... Also, it doesn't make much sense that the issue would be here; this is only checking for hyphenated commands.

Also, if `.split()` was broken, we would want to fix it.

**Comment by Innectic** [comment]
@2Cubed Then why does everything look fine before the split? The issue only occurs after the split happens.

**Comment by 2Cubed** [comment]
Closed in favor of #222.

**Pull request closed without merging**
